---

- name: Consul Configuration
  template:
    src: etc/consul.d/config.json.j2
    dest: "{{consul_config_dir}}/{{item.key}}.json"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    mode: "0644"
    #validate: "{{consul_bin}} configtest -config-file {{consul_config_dir}}/%s"
  with_dict: "{{consul_config}}"
  notify: consul reload

# vi:ts=2:sw=2:et:ft=yaml
