---

- name: Consul Binary Directory
  file:
    state: directory
    name: "{{consul_dest}}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    mode: "0750"

- name: Consul Config Directory
  file:
    state: directory
    name: "{{consul_config_dir}}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    mode: "0750"

- name: Consul Data Directory
  file:
    state: directory
    name: "{{consul_data_dir}}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    mode: "0750"

- name: Consul Web UI Directory
  file:
    state: directory
    name: "{{consul_ui_dir}}"
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    mode: "0750"
  when: consul_ui_enabled


# vi:ts=2:sw=2:et:ft=yaml
